expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('transaction.urls')),
    path("user/", include('user.urls'))
]

transaction/urls.py
from django.urls import path
from . import views 

app_name = "transaction"
urlpatterns = [
    path('', views.homeFn, name='homepage'),
    path('delete/<uuid:id>/', views.delete_transaction, name='delete_tr'),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='registration'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user),
]

transaction/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

# Create your models here.

class BaseModel(models.Model):
    uuid = models.UUIDField(primary_key=True, default = uuid.uuid4, editable= False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Transaction(BaseModel):
    description = models.CharField(max_length=100)
    amount = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

user/models.py
from django.db import models

# Create your models here.

transaction/views.py
from django.shortcuts import render, redirect
from .models import Transaction
from django.db.models import Sum, Case, When, DecimalField
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required
def homeFn(request):
    print(request.user)
    if request.method == "POST":
        print(request.POST)
        description = request.POST.get("description")
        amount = request.POST.get("amount")

        Transaction.objects.create(description = description , amount = amount, user = request.user)
        return redirect('transaction:homepage')
    transaction_sum = Transaction.objects.filter(user = request.user).aggregate(Sum('amount'))['amount__sum']
    if transaction_sum is None:
        transaction_sum = 0
    total = Transaction.objects.filter(user = request.user).aggregate(
        income = Sum(Case(
            When(amount__gte = 0, then='amount'),
            default=0,
            output_field=DecimalField()
        )),
        expense = Sum(Case(
            When(amount__lt = 0, then='amount'),
            default=0,
            output_field=DecimalField()
        ))
    )
    all_transactions = Transaction.objects.filter(user = request.user).order_by('-created_at')

    print(total)

    return render(request,'home.html', {'transaction_sum': transaction_sum, 'transaction_objs': all_transactions, 'income_sum': total['income'], 'expense_sum': total['expense']})

def delete_transaction(request, id):
    item_to_delete = Transaction.objects.filter(pk = id)
    if item_to_delete.exists():
        item_to_delete.delete()
    return redirect('transaction:homepage')

user/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
# Create your views here.

def register(request):
    if request.method == "POST":
        firstname  = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = User.objects.filter(Q(email = email) | Q(username = username))
        if user.exists():
            messages.info(request, "User exists with same username / email")
            return redirect('registration')
        user = User.objects.create_user(username=username, first_name = firstname, last_name = lastname, email = email , password = password)
        login(request, user)
        return redirect('transaction:homepage')
        # create_user method handles password encryption . if using normal create method , then use set_password(pwd) to create encrypted password
    return render(request, 'registration.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user_obj = User.objects.filter(username = username)
        if not user_obj.exists():
            messages.error(request, "User doesn't exist!")
            return redirect("login_user")
        user_obj = authenticate(username = username, password = password)
        if not user_obj:
            messages.error(request , "Wrong credentials!")
            return redirect('login_user')
        login(request, user_obj)
        return redirect('transaction:homepage')
    return render(request, 'login_page.html')

def logout_user(request):
    logout(request)
    return redirect('login_user')
        

transaction/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Transactions</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        {% if request.user.is_authenticated  %}
        <a class="center" href="user/logout/">Logout</a>
        {% endif %}
        <h2>Your Balance: </h2> 
        <p class="balance">{{ transaction_sum }}</p>

        <div class="wrapper">
            <div class="income">
            <h3>Income</h3>
            {% if income_sum%}
            <p>{{income_sum}}</p>
            {% else %}
            <p>0</p>
            {% endif %}
            </div>
            <div class="expense">
            <h3>Expense</h3>
            {% if expense_sum%}
            <p>{{expense_sum}}</p>
            {% else %}
            <p>0</p>
            {% endif %}
            </div>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            <label>Description</label>
            <input type="text" name="description" required>

            <label>Amount</label>
            <input type="number" name="amount" required>

            <button class="btn-submit" type="submit">Add Transaction</button>
        </form>
        <h3>Transactions</h3>
        <div class="transactions">
            
            {% for obj in transaction_objs %}
            {% if obj.uuid%}
            <form action="{% url 'transaction:delete_tr' obj.uuid %}" method="post">
            {% csrf_token %}
                <div class="transaction {% if obj.amount < 0 %}negative{% else %}possitive{% endif %}">
                    <span>{{ obj.description }}</span>
                    <span class="cross">{{ obj.amount }}</span>
                    <button class="submit-btn" type = "submit">X</button>
                </div>
            </form>
            {% endif %}
            {% empty %}
                <p class="empty">No transactions yet</p>
            {% endfor %}
        </div>
    </div>
</body>
</html>

user/templates/login_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Login</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">



    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.0/examples/sign-in/signin.css" rel="stylesheet">
</head>

<body class="text-center">

    <main class="form-signin">
        <form method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Please Login</h1>
            <div class="form-floating">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username">
                <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingPassword"
                    placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>
            <div>
                {% for message in messages %}
                {{message}}
                {% endfor %}
            </div class="">
            <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
        </form>
        <p>New User ? <a href="{% url 'registration'%}">Register</a></p>
    </main>
</body>

</html>

user/templates/registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Registration</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">



    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.0/examples/sign-in/signin.css" rel="stylesheet">
</head>

<body class="text-center">

    <main class="form-signin">
        <form method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Please Register</h1>

            <div class="form-floating">
                <input type="text" name="firstname" class="form-control" id="floatingInput" placeholder="First Name">
                <label for="floatingInput">First Name</label>
            </div>
            <div class="form-floating">
                <input type="text" name="lastname" class="form-control" id="floatingInput" placeholder="Last Name">
                <label for="floatingInput">Last Name</label>
            </div>
            <div class="form-floating">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username">
                <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="Email address">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingPassword"
                    placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>
            <div>
                {% for message in messages %}
                {{message}}
                {% endfor %}
            </div class="">
            <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
        </form>
    </main>
</body>

</html>